In [31]:
import pandas as pd

In [32]:
pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\roaming\python\python313\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\dell\appdata\roaming\python\python313\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\dell\appdata\roaming\python\python313\site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
pip install matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\dell\appdata\roaming\python\python313\site-packages (3.11.1)
Requirement already satisfied: seaborn in c:\users\dell\appdata\roaming\python\python313\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\dell\appdata\roaming\python\python313\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: tzdata in c:\users\dell\appdata\roaming\python\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
import pandas as pd

In [37]:
import matplotlib.pyplot as plt

In [38]:
import seaborn as sns

In [39]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\dell\appdata\roaming\python\python313\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
username = 'root'
password = '12345'   
host = 'localhost'
database = 'capstone'

In [41]:
import pandas as pd
from sqlalchemy import create_engine

In [42]:
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}/{database}')
engine

Engine(mysql+pymysql://root:***@localhost/capstone)

In [43]:
customers = pd.read_sql('select * from customers', engine)
customers

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NA\r,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NA\r,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NA\r,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NA\r,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003\r,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820
...,...,...,...,...,...,...,...,...,...
1440,1441,Jamaal,Morrison,NA\r,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301
1441,1442,Cassie,Cline,NA\r,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201
1442,1443,Lezlie,Lamb,NA\r,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722
1443,1444,Ivette,Estes,NA\r,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424
1444,1445,Ester,Acevedo,NA\r,ester.acevedo@gmail.com,671 Miles Court,San Lorenzo,CA,94580

In [44]:
orders=pd.read_sql('select * from orders', engine)
orders

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6
...,...,...,...,...,...,...,...,...
1610,1611,6,3,2018-09-06,2018-09-06,None,2,7
1611,1612,3,3,2018-10-21,2018-10-21,None,1,3
1612,1613,1,3,2018-11-18,2018-11-18,None,2,6
1613,1614,135,3,2018-11-28,2018-11-28,None,3,8
1614,1615,136,3,2018-12-28,2018-12-28,None,3,8

In [45]:
order_items=pd.read_sql('select * from order_items', engine)
order_items

      order_id  item_id  product_id  quantity  list_price  discount
0            1        1          20         1      599.99      0.20
1            1        2           8         2     1799.99      0.07
2            1        3          10         2     1549.00      0.05
3            1        4          16         2      599.99      0.05
4            1        5           4         1     2899.99      0.20
...        ...      ...         ...       ...         ...       ...
4717      1614        2         159         2     2299.99      0.07
4718      1614        3         213         2      269.99      0.20
4719      1615        1         197         2     2299.99      0.20
4720      1615        2         214         1      899.99      0.07
4721      1615        3         182         1     2499.99      0.20

[4722 rows x 6 columns]

## Basic EDA (Exploratory Data Analysis)

In [46]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1445 non-null   int64
 1   first_name   1445 non-null   str
 2   last_name    1445 non-null   str
 3   phone        1445 non-null   str
 4   email        1445 non-null   str
 5   street       1445 non-null   str
 6   city         1445 non-null   str
 7   state        1445 non-null   str
 8   zip_code     1445 non-null   str
dtypes: int64(1), str(8)
memory usage: 101.7 KB

In [47]:
orders.describe()

          order_id  customer_id  order_status     store_id     staff_id
count  1615.000000  1615.000000   1615.000000  1615.000000  1615.000000
mean    808.000000   654.171517      3.778947     1.892260     5.855108
std     466.354658   443.229967      0.693430     0.558395     1.913899
min       1.000000     1.000000      1.000000     1.000000     2.000000
25%     404.500000   237.000000      4.000000     2.000000     6.000000
50%     808.000000   638.000000      4.000000     2.000000     6.000000
75%    1211.500000  1041.500000      4.000000     2.000000     7.000000
max    1615.000000  1445.000000      4.000000     3.000000     9.000000

In [48]:
customers.describe()

       customer_id
count  1445.000000
mean    723.000000
std     417.279882
min       1.000000
25%     362.000000
50%     723.000000
75%    1084.000000
max    1445.000000

In [49]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1615 non-null   int64
 1   customer_id    1615 non-null   int64
 2   order_status   1615 non-null   int64
 3   order_date     1615 non-null   object
 4   required_date  1615 non-null   object
 5   shipped_date   1445 non-null   object
 6   store_id       1615 non-null   int64
 7   staff_id       1615 non-null   int64
dtypes: int64(5), object(3)
memory usage: 101.1+ KB

In [50]:

customers['state'].value_counts()

state
NY    1019
CA     284
TX     142
Name: count, dtype: int64

In [51]:
orders['order_status'].value_counts()

order_status
4    1445
2      63
1      62
3      45
Name: count, dtype: int64

In [52]:
merged = orders.merge(order_items, on='order_id')
merged

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,item_id,product_id,quantity,list_price,discount
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,1,20,1,599.99,0.20
1,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,2,8,2,1799.99,0.07
2,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,3,10,2,1549.00,0.05
3,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,4,16,2,599.99,0.05
4,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,5,4,1,2899.99,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4717,1614,135,3,2018-11-28,2018-11-28,None,3,8,2,159,2,2299.99,0.07
4718,1614,135,3,2018-11-28,2018-11-28,None,3,8,3,213,2,269.99,0.20
4719,1615,136,3,2018-12-28,2018-12-28,None,3,8,1,197,2,2299.99,0.20
4720,1615,136,3,2018-12-28,2018-12-28,None,3,8,2,214,1,899.99,0.07
4721,1615,136,3,2018-12-28,2018-12-28,None,3,8,3,182,1,2499.99,0.20

In [53]:
merged['total_price'] = merged['quantity'] * merged['list_price'] * (1 - merged['discount'])
merged['total_price']

0        479.9920
1       3347.9814
2       2943.1000
3       1139.9810
4       2319.9920
          ...
4717    4277.9814
4718     431.9840
4719    3679.9840
4720     836.9907
4721    1999.9920
Name: total_price, Length: 4722, dtype: float64

In [54]:
reference_date = merged['order_date'].max() + dt.timedelta(days=1)
reference_date

NameError: name 'dt' is not defined

In [ ]:
import datetime as dt

In [ ]:
rfm = merged.groupby('customer_id').agg(
    recency=('order_date', lambda x: (reference_date - x.max()).days),
    frequency=('order_id', 'nunique'),
    monetary=('total_price', 'sum')
).reset_index()
rfm

In [ ]:
rfm.describe()

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [ ]:
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['recency', 'frequency', 'monetary']])

In [ ]:
scaler
rfm_scaled

In [ ]:
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
rfm['cluster'] = kmeans.fit_predict(rfm_scaled)

In [ ]:
rfm['cluster'].value_counts()

In [ ]:
cluster_summary = rfm.groupby('cluster')[['recency', 'frequency', 'monetary']].mean().round(2)
cluster_summary

In [ ]:
segment_map = {
    0: 'At Risk',
    1: 'Medium Value',
    2: 'High Value'
}

In [ ]:
segment_map

In [ ]:
rfm['segment'] = rfm['cluster'].map(segment_map)
rfm[['customer_id', 'recency', 'frequency', 'monetary', 'segment']].head(10)

In [ ]:
final_segments = rfm[['customer_id', 'recency', 'frequency', 'monetary', 'segment']]
final_segments

In [ ]:
final_segments.to_sql('customer_segments', con=engine, if_exists='replace', index=False)

In [ ]:
("Uploaded", len(final_segments), "rows to customer_segments table")

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
segment_counts = rfm['segment'].value_counts()

# Chart 1 — Number of Customers by Segment

In [ ]:
plt.figure(figsize=(8, 5))
plt.bar(segment_counts.index, segment_counts.values,color=({'green','red','purple'}))
plt.title('Number of Customers by Segment')
plt.xlabel('Customer Segment')
plt.ylabel('Number of Customers')
plt.grid(color='black')
plt.show()

# Chart 2 — Average Revenue by Segment

In [58]:
avg_monetary = rfm.groupby('segment')['monetary'].mean()
avg_monetary

NameError: name 'rfm' is not defined

In [56]:
plt.figure(figsize=(8, 5))
plt.bar(avg_monetary.index, avg_monetary.values,color=({'brown','pink','grey'}))
plt.title('Average Revenue per Customer by Segment')
plt.xlabel('Customer Segment')
plt.ylabel('Average Revenue')
plt.grid(color='black')
plt.show()

NameError: name 'avg_monetary' is not defined

In [ ]:
import matplotlib.pyplot as plt

In [57]:
avg_monetary

NameError: name 'avg_monetary' is not defined